.TH LIBFT 3 "2024-09-16" "sede-san" "42 Manual"

.SH NAME
libft - Library with some re-created standard C library functions, as well as more implemented. 

.SH SYNOPSIS
.B #include \(dqlibft.h\(dq

.SH DESCRIPTION
\fBLibft\fP is the first project of the 42 Cursus. The objective of this project is to understand the fundamentals of some of the most commonly used standard C library functions. Additionally, this project allows for the inclusion of personal functions that may be useful for other projects.

.SH SEE ALSO
\fBlibc\fP(7)

.SH BUGS
No known bugs to date.

.SH AUTHOR
Both libft and this manual were written by sede-san.